robosound {
name="bebop"
extension="rbs"
tempo="200"
}
#Tempo is in BPM

robo sound bebop loop {
synth.sound.play(repeat="1" tone="F#" mod="SpaceShuttle"); 
wait(0.1);
synth.sound.play(repeat="1" tone="C" mod="SpaceShuttle");
wait(0.1);
}
